apiVersion: v1
kind: Service
metadata:
  name: employeecollection-coll-4af80c20c5764b099f36b0504b29c9a6-srv
spec:
  selector:
    app: employeecollection-coll-4af80c20c5764b099f36b0504b29c9a6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9028
  type: ClusterIP